DROP TABLE users IF EXISTS;
DROP TABLE url IF EXISTS;
DROP TABLE user_url_dtl IF EXISTS;
DROP TABLE module IF EXISTS;
DROP TABLE environment_master IF EXISTS;
DROP TABLE role IF EXISTS;
DROP TABLE module_env IF EXISTS;