package com.core.entity;


// Generated Jan 19, 2012 5:46:43 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BizGroup generated by hbm2java
 */

@NamedQuery(name ="getGrp",
query ="select g from Test2 g where g.col1= :col1")
@Entity
@Table(name = "TEST2")
public class Test2 implements java.io.Serializable {

	private int col1;
	private String col2;
	private Date col3;

	public Test2() {
	}

	public Test2(int col1) {
		this.col1 = col1;
	}

	public Test2(int col1, String col2, Date col3) {
		this.col1 = col1;
		this.col2 = col2;
		this.col3 = col3;
	}

	@Id
	@Column(name = "COL1", unique = true, nullable = false)
	public int getCol1() {
		return this.col1;
	}

	public void setCol1(int col1) {
		this.col1 = col1;
	}

	@Column(name = "COL2", length = 50)
	public String getCol2() {
		return this.col2;
	}

	public void setCol2(String col2) {
		this.col2 = col2;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "COL3", length = 10)
	public Date getCol3() {
		return this.col3;
	}

	public void setCol3(Date col3) {
		this.col3 = col3;
	}

}
